<a href="https://colab.research.google.com/github/sayaliphatak9628/Python/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
arr=np.array(
    [
     [1,2,3],
     [2,3,4]
    ]
)
print(arr)

[[1 2 3]
 [2 3 4]]


In [5]:
#creating list from tuple
arr=np.array((1,2,3,4))
print(arr)

[1 2 3 4]


In [6]:
arr=np.array(
    [
        [-1, 2, 0, 4],
        [4, -0.5, 6, 0],
        [2.6, 0, 7, 8],
        [3, -7, 4, 2.0]
    ]
)
print(arr)

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [7]:
#using slicing method
sliced_arr=arr[:-1,::3]
print(sliced_arr)

[[-1.   4. ]
 [ 4.   0. ]
 [ 2.6  8. ]]


In [8]:
#printing index at specific indices
index_arr=arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]
print(index_arr)

[0. 6. 2. 3.]


In [12]:
a=np.array(
    [
     [1,2],
     [3,4]
    ]
)
print(a)

[[1 2]
 [3 4]]


In [13]:
b=np.array(
    [
     [4,3],
     [2,1]
    ]
)
print(b)

[[4 3]
 [2 1]]


In [15]:
#adding 1 to every element
a=a+1
print(a)

[[3 4]
 [5 6]]


In [17]:
#subtracting 1 from every element
b=b-1
print(b)

[[ 2  1]
 [ 0 -1]]


In [24]:
print(a.sum())
print(np.multiply(a,b)) #multiply
print(np.matmul(a,b)) #matrix multiplication
print(np.linalg.inv(a)) #inverse of matrix
print(a.transpose())

18
[[ 6  4]
 [ 0 -6]]
[[ 6 -1]
 [10 -1]]
[[-3.   2. ]
 [ 2.5 -1.5]]
[[3 5]
 [4 6]]
